version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8787:3000"
    environment:
      - NODE_ENV=staging
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - '.:/app'

  redis:
    image: "redis:alpine"
